name: EGGPU
channels:
  - rapidsai
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10.20
  - cuda-version=12.8
  - cuda-toolkit=12.8
  - cmake>=3.26
  - ninja
  - numpy=2.2.6
  - pandas=2.3.3
  - scipy=1.15.3
  - networkx=3.4.2
  - matplotlib=3.10.9
  - psutil=7.2.2
  - nvidia-ml-py=13.595.45
  - cupy=14.0.1
  - cudf=26.02.01
  - cugraph=26.02.00
  - nx-cugraph=26.02.00
  - pip
  - pip:
      - igraph==1.0.0
      - nvitop==1.7.0
